### ISSUE TITLE
Error when using CyMLT : 

### ISSUE THREAD

**Issue by pradal** [AgriculturalModelExchangeInitiative/PyCrop2ML#240]
When try to transpile a crop2ML model to a language, I have the error:

``` python
Traceback (most recent call last):
  File "/Users/pradal/miniforge3/envs/cropml/bin/cyml", line 33, in <module>
    sys.exit(load_entry_point('pycropml', 'console_scripts', 'cyml')())
  File "/Users/pradal/devlp/git/PyCrop2ML/src/pycropml/main.py", line 133, in main
    status = transpile_package(sourcef, language)
  File "/Users/pradal/devlp/git/PyCrop2ML/src/pycropml/cyml.py", line 75, in transpile_package
    if not output.isdir():
AttributeError: 'Path' object has no attribute 'isdir'
```

**Comment by pradal** [comment]
Fix with PR #241
